config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages do
    member do
      post 'publish'
    end
  end

  get 'publications/:genurl' => 'pages#show_public_page', as: 'public'
  root 'pages#new'
end

app/models/page.rb
class Page < ActiveRecord::Base



  belongs_to :user

validates :headline, :presence => true, :length => {
  :maximum => 12,
  :tokenizer => lambda { |str| str.scan(/\w+/) },
  :too_long  => "Headline should be maximum 12 words"
}

validates :content, :length => {
  :maximum => 36,
  :tokenizer => lambda { |str| str.scan(/\w+/) },
  :too_long  => "Content should be maximum 36 words"
}


has_attached_file :picture,
    styles: { large: "800x800>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/






H1_STYLES = {

["wagon", "accelerator", "innovate", "innovation", "programming", "code", "tech", "start", "bootcamp", "internet", "app"] => "tech",
["fashion", "sale", "clothing", "bags", "shoes", "buotique", "%", "shop", "off", "special", "pants"] => "fashion",
["surf", "vacation", "flight", "hotel", "package", "destination", "destinations", "asia", "america", "europe", "africa", "travel"  ] => "travel",
["show", "live", "tickets", "concert", "beers", "tour", "venue", "get", "warm up", "warm-up"] => "music",
["class", "lecture", "professor", "topic", "subject","classroom", "university", "campus", "college" ] => "academic",
["love", "wedding", "anniversary", "happy birthday", "wish","kisses", "hugs", "you" ] => "personal",
["check" ] => "fashion-demo"


}



  def style
  @style ||= detect_style(content_for_style, H1_STYLES, "neutral")
  end

def content_for_style
  "#{headline} #{content}".downcase
end


def h1_style
  style+variant
end

def backgroundimage
  "bg-"+style+variant
end

def variant
  rand(1..3).to_s
end

def detect_style(text, rules, default_style)
  rules.each do |keywords, style|
    return style if keywords.any? { |kw| text.include?(kw) }
  end

  default_style
end

  def published?
    url != nil
  end

def set_url
  self.url = rand(1..1000)

end



def show_button?
btn != "Add Button"
end





end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
has_many :pages, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy, :publish]

  before_filter :authenticate_user!, only: [:publish]
  # GET /pages
  # GET /pages.json






  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])
    @page_bg = @page.bg_style || @page.backgroundimage
    @page_h1 = @page.headline_style || @page.h1_style
    @custom_image = "style=\"background-image: url('#{@page.picture.url}')\"" if @page.picture.present?

  end

  def publish

    @page.update_attributes(page_params)

    @user = current_user
    @page_h1 = params[:h1_style]
    @page_bg = params[:bg_style]
    @page.headline_style = params[:h1_style]
    @page.bg_style = params[:bg_style]
    @page.user = @user
    @page.set_url
    @page.imgurl = findimage

    @page.save!

    # redirect_to public_path(genurl: @page.url)

    redirect_to @page
  end

  def findimage

    if @page.picture.present?
      @page.picture.url
    else
      view_context.image_path("#{@page.bg_style}.jpg")
    end

  end

  def select_bg_style
    if @page.picture.present?
    @custom_image
    else
    params[:bg_style]
    end

  end





  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def show_public_page
      @page = Page.find_by(url: params[:genurl])
      @page_bg = @page.bg_style
      @page_h1 = @page.headline_style
      @custom_image = "style=\"background-image: url('#{@page.imgurl}')\""
      render :publish
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:url, :headline, :content, :picture, :btn)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= yield(:title) || "Your App name" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <% # javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
   <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="<%= (yield(:description) || "").squish %>">
<!-- <link href='https://fonts.googleapis.com/css?family=Quicksand:400,300,700|Source+Code+Pro|Abril+Fatface|Sirin+Stencil|Roboto:400,900,700,300|Knewave' rel='stylesheet' type='text/css'> -->

<%= yield(:head) %>
<link href='https://fonts.googleapis.com/css?family=Source+Code+Pro|Knewave|Abril+Fatface|Sirin+Stencil|Quicksand|Pacifico|Amatic+SC|Dancing+Script|Permanent+Marker|Handlee|Poiret+One|Droid+Sans|Fjalla+One|Vollkorn|Voltaire|Kelly+Slab|Buda:300|Roboto|Playfair+Display' rel='stylesheet' type='text/css'>

<!-- supersized gallery! -->

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />



<!-- supersized gallery! -->





</head>
<body>


  <%= yield %>

  <%= yield(:after_js) %>
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->
</body>
</html>

app/views/layouts/application_copy1.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= yield(:title) || "Your App name" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="<%= (yield(:description) || "").squish %>">
<!-- <link href='https://fonts.googleapis.com/css?family=Quicksand:400,300,700|Source+Code+Pro|Abril+Fatface|Sirin+Stencil|Roboto:400,900,700,300|Knewave' rel='stylesheet' type='text/css'> -->

<link href='https://fonts.googleapis.com/css?family=Source+Code+Pro|Knewave|Abril+Fatface|Sirin+Stencil|Quicksand|Pacifico|Amatic+SC|Dancing+Script|Permanent+Marker|Handlee|Poiret+One|Droid+Sans|Fjalla+One|Vollkorn|Voltaire|Kelly+Slab|Buda:300|Roboto|Playfair+Display' rel='stylesheet' type='text/css'>


</head>
<body>
<!-- Add these line for detecting device width -->
<%= render "shared/navbar" %>

  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= yield(:after_js) %>
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->
</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page, html: { multipart: true }) do |f| %>
  <div class="forma">
    <%= f.text_field :headline, :placeholder => "What is Your Headline?", :class => "login"%>
    <%= f.text_field :content, :placeholder => "Add Some Details", :class => "login2"%>
    <%= f.submit "Add Logo", :class => "button add" %>
    <%= f.select :btn, ['Add Button','Get a Promo Code','Subscribe', 'Buy','Join Mailing list'], {}, :class => "btn_dropdown" %>

    <div class="fileinput-button add">
      <span>Add Image</span>
      <%= f.file_field :picture, :placeholder => "Add Image"  %>
    </div>


    <%= f.submit "Beam it", :class => "button beam" %><br>

    <div class="notice"><%= @page.errors[:headline].to_sentence %><br><%= @page.errors[:content].to_sentence %></div>
  </div>
<% end %>

app/views/pages/_formcopy.html.erb
<%= form_for(@page, html: { multipart: true }) do |f| %>
  <div class="forma">
    <%= f.text_field :headline, :placeholder => "What is Your Headline?", :class => "login"%>
    <%= f.text_field :content, :placeholder => "Add Some Details", :class => "login2"%>
    <%= f.submit "Add Logo", :class => "button add" %>
    <%= f.select :btn, ['Add Button','Get a Promo Code','Subscribe', 'Buy','Join Mailing list'], {}, :class => "btn_dropdown" %>

    <div class="fileinput-button add">
      <span>Add Image</span>
      <%= f.file_field :picture, :placeholder => "Add Image"  %>
    </div>


    <%= f.submit "Beam it", :class => "button beam" %><br>

    <div class="notice"><%= @page.errors[:headline].to_sentence %><br><%= @page.errors[:content].to_sentence %></div>
  </div>
<% end %>

app/views/pages/copyoldform.html.erb
<%= form_for(@page, html: { multipart: true }) do |f| %>
  <div class="forma">
    <%= f.text_field :headline, :placeholder => "What is Your Headline?", :class => "login"%>
    <%= f.text_field :content, :placeholder => "Add Some Details", :class => "login2"%>
    <%= f.submit "Add Logo", :class => "button add" %>
    <%= f.select :btn, ['Add Button','Get a Promo Code','Subscribe', 'Buy','Join Mailing list'], {}, :class => "btn_dropdown" %>

    <div class="fileinput-button add">
      <span>Add Image</span>
      <%= f.file_field :picture, :placeholder => "Add Image"  %>
    </div>


    <%= f.submit "Beam it", :class => "button beam" %><br>

    <div class="notice"><%= @page.errors[:headline].to_sentence %><br><%= @page.errors[:content].to_sentence %></div>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<div class="show"></div>

<p id="notice"><%= notice %></p>


<table class='table-bordered paddingit'>
  <thead class='paddingit'>
    <tr>
    <th class='paddingit'>User_id</th>
      <th class='paddingit'>Url</th>
      <th class='paddingit'>Headline</th>
      <th class='paddingit'>Headline_style</th>
      <th class='paddingit'>Content</th>
      <th class='paddingit'>Content_style</th>
      <th class='paddingit'>Bg_style</th>
      <th class='paddingit'>Image URL</th>
      <th class='paddingit'>Button</th>
      <th class='paddingit'>Btn_style</th>
      <th class='paddingit'>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
<td><% if page.user %>
<%= page.user.email %>
<% end %>
</td>
        <td class='paddingit'><%= page.url %></td>
        <td class='paddingit'><%= page.headline %></td>
        <td class='paddingit'><%= page.headline_style %></td>
        <td class='paddingit'><%= page.content %></td>
        <td class='paddingit'><%= page.content_style %></td>
        <td class='paddingit'><%= page.bg_style %></td>
        <td class='paddingit'><%= page.imgurl %></td>
        <td class='paddingit'><%= page.btn %></td>
         <td class='paddingit'><%= page.btn_style %></td>
        <td class='paddingit'><%= page.published %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<div class="full2">

<div class="navi3"><%= image_tag("beamop_white.png", :alt => "beamop", :class => "logo") %></div>

<div class="formdiv"><%= render 'form' %></div>
<div class="patxt"><p style ="font-size:3vw;">⤵</p></div>
<div class="bigtxt">GIVE US YOUR CONTENT, WE'LL MAKE IT REACH THE APPROPPRIATE AUDIENCE INSTANTLY
<br>-<br>
</div>

<div class="patxt">
Beamop is your personal design and ad placing agency. Designing and placing visual communications online can be a challenge.
To make things simpler we've developed a design generator and ad placing algorithm to enable our users to quickly design and publish their content online.
</div>

<div class="icons"><i class="fa fa-facebook pericon"></i><i class="fa fa-linkedin-square pericon"></i><i class="fa fa-instagram pericon"></i><i class="fa fa-twitter pericon"></i><i class="fa fa-google-plus pericon"></i></div>

<div class="bigtxt2">
How Can Small Businesses Visually Communicate Online?
</div>

<div class="bigtxt">-</div>
<%= image_tag("diagram.png", width: '80%', class: "img-responsive diagram") %>
<br>
<div class="footer">Copyright © 20013–2015 Beamop LLCiron Ross | savonge@gmail.com | +32495766575 </div>
<br>
</div>


<script type="text/javascript">
$(document).ready(function($){

  $.supersized({

    // Functionality
    slideshow               :   1,      // Slideshow on/off
    autoplay        : 1,      // Slideshow starts playing automatically
    start_slide             :   1,      // Start slide (0 is random)
    stop_loop       : 0,      // Pauses slideshow on last slide
    random          :   0,      // Randomize slide order (Ignores start slide)
    slide_interval          :   500,   // Length between transitions
    transition              :   1,      // 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
    transition_speed    : 5000,   // Speed of transition
    new_window        : 1,      // Image links open in new window/tab
    pause_hover             :   0,      // Pause slideshow on hover
    keyboard_nav            :   1,      // Keyboard navigation on/off
    performance       : 1,      // 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
    image_protect     : 1,      // Disables image dragging and right click with Javascript

    // Size & Position
    min_width           :   0,      // Min width allowed (in pixels)
    min_height            :   0,      // Min height allowed (in pixels)
    vertical_center         :   1,      // Vertically center background
    horizontal_center       :   1,      // Horizontally center background
    fit_always        : 0,      // Image will never exceed browser width or height (Ignores min. dimensions)
    fit_portrait          :   1,      // Portrait images will not exceed browser height
    fit_landscape     :   0,      // Landscape images will not exceed browser width

    // Components
    slide_links       : 'num',  // Individual links for each slide (Options: false, 'number', 'name', 'blank')
    thumb_links       : 0,      // Individual thumb links for each slide
    thumbnail_navigation    :   0,      // Thumbnail navigation
    slides          :   [     // Slideshow Images
                      {image : '<%= image_url("blur1.jpg") %>', title : '', thumb : '', url : ''},
                      {image : '<%= image_url("blur2.jpg") %>', title : '', thumb : '', url : ''},
                      {image : '<%= image_url("blur3.jpg") %>', title : '', thumb : '', url : ''},
                      {image : '<%= image_url("blur4.jpg") %>', title : '', thumb : '', url : ''},

                      {image : '<%= image_url("blur5.jpg") %>', title : '', thumb : '', url : ''}
                  ],

    // Theme Options
    progress_bar      : 1,      // Timer for each slide
    mouse_scrub       : 0

  });

  function MM_preloadImages() { //v3.0
    var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
      var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
      if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
  }

});


</script>

app/views/pages/publish.html.erb
<% content_for(:head) do %>
<meta property="og:url"                content="<%= public_url(genurl: @page.url) %>" />
<meta property="og:type"               content="article" />
<meta property="og:title"              content="<%= @page.headline %>" />
<meta property="og:description"        content="<%= @page.content %>" />
<meta property="og:image"              content="<%= @page.imgurl %>" />

<% end  %>


<div class="parent <%= @page_bg %>" <%= raw(@custom_image) %>>
  <div class="child <%= @page_h1 %>">
<%= @page.headline %>
  <p class="bodytxt ">
  <%= @page.content %><br><br>
 <% if @page.show_button? %>
    <button type="button" class="relative_button"><%= @page.btn %></button>
   <% end %>

  </p>
</div>

app/views/pages/show.html.erb
<nav class="navbar navbar-default navi2">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= new_page_path %>"><%= image_tag("beamop_grey.png", :alt => "beamop", :class => "logo2") %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

 <ul class="nav navbar-nav navbar-left">
        <% if current_user %>
        <li>
        <%= link_to "Logout", destroy_user_session_path, method: "delete"  %>
        </li>
        <% else %>
        <li> <%= link_to "Login", user_session_path  %></li>
        <% end %>
</ul>



       <ul class="nav navbar-nav navbar-center centerlinks">
         <li><%= link_to "← Back", new_page_path, :method => :get %></li>
            <li><%= link_to "Next Design", page_path(@page, h1_style: @page_h1, bg_style: @page_bg) %></li>

       </ul>


      <ul class="nav navbar-nav navbar-right">

      <!-- <form class="navbar-form navbar-left" role="search" action='<%= publish_page_path(@page, h1_style: @page_h1, bg_style: @page_bg) %>' method='post'> -->
      <%= form_for(@page, url: publish_page_path(@page, h1_style: @page_h1, bg_style: @page_bg), method: :post, html: { multipart: true, class: 'navbar-form' }) do |f| %>
        <div class="form-group">
          <%= f.file_field :picture, :placeholder => "Add Image", class: 'form-control'  %>

        </div>

<div class="form-group">
         <%= f.select :btn, ['Add Button','Get a Promo Code','Subscribe to Our Newsletter', 'Buy','Join Mailing list'], {}, class: 'form-control' %>
</div>

        <button type="submit" class="btn btn-default">Publish Campaign</button>
      <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if @page.published? %>
<div id="gradient"></div>
<div class="showurl" id="published">
<table class="tg">
  <tr>
    <th class="tg-baqh" style="width:20%; text-align:right;"><iframe class="thumbframe1" src="<%= public_url(genurl: @page.url) %>"></iframe></th>
    <th class="tg-baqh"style="width:60%; border-left:black solid medium; border-right:black solid medium;"><iframe class="thumbframe2" src="<%= public_url(genurl: @page.url) %>"></iframe></th>
    <th class="tg-baqh"style="width:20%"><iframe class="thumbframe3" src="<%= public_url(genurl: @page.url) %>"></iframe></th>
  </tr>
  <tr>
    <td class="tg-baqh" colspan="3">
      <%= link_to "#{public_url(genurl: @page.url)}", public_url(genurl: @page.url), :target => "_blank" %> |
       <a class="btn btn-social-icon btn-facebook" href="<%= "https://www.facebook.com/sharer/sharer.php?u=" + public_url(genurl: @page.url) %>"><i class="fa fa-facebook"></i></a>
       <a class="btn btn-social-icon btn-twitter" href="<%= "https://www.facebook.com/sharer/sharer.php?u=" + public_url(genurl: @page.url) %>"><i class="fa fa-twitter"></i></a>
        <a class="btn btn-social-icon btn-linkedin" href="<%= "https://www.facebook.com/sharer/sharer.php?u=" + public_url(genurl: @page.url) %>"><i class="fa fa-linkedin"></i></a>
        <a class="btn btn-social-icon btn-instagram" href="<%= "https://www.facebook.com/sharer/sharer.php?u=" + public_url(genurl: @page.url) %>"><i class="fa fa-instagram"></i></a>


    </td>
    <td></td>
  </tr>
</table>


</div>

<% end %>




<div class="parent <%= @page_bg %>" <%= raw(@custom_image) %>>
  <div class="child <%= @page_h1 %>">
<%= @page.headline %>
  <p class="bodytxt ">
  <%= @page.content %><br><br>
  <% if @page.show_button? %>
    <button type="button" class="relative_button"><%= @page.btn %></button>
   <% end %>
  </p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navi2">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

       <ul class="nav navbar-nav navbar-center centerlinks">
         <li><%= link_to "← Back", new_page_path, :method => :get, :class => "navilinks" %></li>

       </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
      <li>
            <%= link_to "Logout", destroy_user_session_path, method: "delete", :class => "navilinks" %>
      </li>
     <% else %>
     <li> <%= link_to "Login", user_session_path, :class => "navilinks" %></li>
          <% end %>


        <li><%= link_to "Publish Campaign", publish_page_path(@page), method: "post", :class => "navilinks" %></li>
        <!-- <li class="dropdown navilinks">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Publish Campaign <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul> -->
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>